[package]
name = "aoc-2023-8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
num = "0.4.1"
thiserror="*"
winnow = { version = "*", features = ["alloc"] }
